# This is a basic workflow to help you get started with Actions

name: Release abg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run go mod tidy
        run: go mod tidy

      - name: Build abg for ${{ matrix.arch }}
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: linux
        run: |
          mkdir -p dist/
          go build -o dist/abg-linux-${{ matrix.arch }} ./cmd/main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: abg-linux-${{ matrix.arch }}
          path: dist/abg-linux-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display files
        run: ls -R dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/abg-linux-amd64
            dist/**/abg-linux-arm64
          token: ${{ secrets.RELEASE_SECRET }}

   
